"""add configurable classification schema

Revision ID: f2d7a17a6e29
Revises: c09225df3432
Create Date: 2026-10-07 19:10:11.604128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d7a17a6e29'
down_revision: Union[str, Sequence[str], None] = 'c09225df3432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name_de', sa.Text(), nullable=False),
    sa.Column('name_fr', sa.Text(), nullable=False),
    sa.Column('name_it', sa.Text(), nullable=False),
    sa.Column('name_rm', sa.Text(), nullable=False),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_it', sa.Text(), nullable=True),
    sa.Column('description_rm', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('classification_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['classification_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_classification_categories_code')
    )
    op.create_index('idx_classification_categories_parent_id', 'classification_categories', ['parent_id'], unique=False)
    op.create_table('affair_classifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('affair_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('classifier_version', sa.String(length=50), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['classification_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affair_id', 'category_id', name='uq_affair_classifications_affair_category')
    )
    op.create_index('idx_affair_classifications_affair_id', 'affair_classifications', ['affair_id'], unique=False)
    op.create_index('idx_affair_classifications_category_id', 'affair_classifications', ['category_id'], unique=False)
    op.create_index('idx_affair_classifications_confidence', 'affair_classifications', ['confidence'], unique=False)
    op.create_table('classification_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['classification_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classification_rules_active', 'classification_rules', ['active'], unique=False)
    op.create_index('idx_classification_rules_category_id', 'classification_rules', ['category_id'], unique=False)
    op.create_index('idx_classification_rules_language', 'classification_rules', ['language'], unique=False)
    op.create_table('classification_evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('classification_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_language', sa.String(length=2), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_term', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['affair_classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['classification_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classification_evidence_classification_id', 'classification_evidence', ['classification_id'], unique=False)
    op.create_index('idx_classification_evidence_rule_id', 'classification_evidence', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_classification_evidence_rule_id', table_name='classification_evidence')
    op.drop_index('idx_classification_evidence_classification_id', table_name='classification_evidence')
    op.drop_table('classification_evidence')
    op.drop_index('idx_classification_rules_language', table_name='classification_rules')
    op.drop_index('idx_classification_rules_category_id', table_name='classification_rules')
    op.drop_index('idx_classification_rules_active', table_name='classification_rules')
    op.drop_table('classification_rules')
    op.drop_index('idx_affair_classifications_confidence', table_name='affair_classifications')
    op.drop_index('idx_affair_classifications_category_id', table_name='affair_classifications')
    op.drop_index('idx_affair_classifications_affair_id', table_name='affair_classifications')
    op.drop_table('affair_classifications')
    op.drop_index('idx_classification_categories_parent_id', table_name='classification_categories')
    op.drop_table('classification_categories')
    # ### end Alembic commands ###
